In [8]:
import pandas as pd 

df = pd.read_csv("res_model.csv")
df.head()

,Model,Type,Train Init Temp,Train Steps,Train Dimension,Train Demand,Train Scheduler,Train Clustering,Dimension,Step,Scheduler,Clustering,Initial Temp,Initial Cost,Final Cost,Gain
0,/Users/jandretti/Documents/PhD/NSA_CVRP_PPO/wa...,Trained,1,100,20,True,step,False,20,100,cyclic,True,1,10.808784,6.056129,4.752656
1,/Users/jandretti/Documents/PhD/NSA_CVRP_PPO/wa...,Trained,1,100,20,True,step,False,20,100,lam,True,1,10.808784,6.043811,4.764974
2,/Users/jandretti/Documents/PhD/NSA_CVRP_PPO/wa...,Trained,1,100,20,True,step,False,20,100,step,True,1,10.808784,5.915554,4.893230
3,/Users/jandretti/Documents/PhD/NSA_CVRP_PPO/wa...,Trained,1,100,20,True,step,False,20,1000,cyclic,True,1,10.808784,5.568490,5.240295
4,/Users/jandretti/Documents/PhD/NSA_CVRP_PPO/wa...,Trained,1,100,20,True,step,False,20,1000,lam,True,1,10.808784,5.496990,5.311795

In [9]:
# Garder uniquement les colonnes spécifiées
new_df = df[['Model','Train Init Temp', 'Train Steps', 'Train Dimension', 'Train Demand', 'Train Scheduler', 'Train Clustering']].copy()
new_df.loc[:, "Model"] = new_df["Model"].apply(lambda x: x.split("/")[-2])
new_df = new_df.drop_duplicates(subset=["Model"])

# Afficher le nouveau DataFrame
new_df.head()

,Model,Train Init Temp,Train Steps,Train Dimension,Train Demand,Train Scheduler,Train Clustering
0,20250206_141623_eygjgypl,1,100,20,True,step,False
162,20250206_150001_n6l44leu,1000,1000,20,True,step,False
324,20250206_182443_zya1og52,100,100,20,True,step,True
486,20250206_190801_1jrf079s,100,1000,20,True,step,False
648,20250206_223451_9neq6qez,1,100,20,True,step,True

In [10]:
new_df.to_csv("model.csv", index=False)